### ISSUE TITLE
"limit"  in Query 

### ISSUE THREAD

**Issue by rhymer211** [aws/aws-sdk-ruby-record#74]
"limit" in query, it seems to be ignored

**Comment by awood45** [comment]
I'd have to see a usage example - it definitely is not ignored by the client, but since it returns an auto-paging enumerable, if you use `#each` directly the client will dutifully keep calling `#query` to get new results.

**Comment by awood45** [comment]
I'm actually working on an extension to aws-record functionality which should make this a bit more intuitive. Stand by...

**Comment by awood45** [comment]
You can use `limit` in the way you're thinking in version `2.0.1` of the library. If you use `#page` on the scan/query response rather than `#each` or an Enumerable method, you'll get your first page of responses only. If you wish to call again for the next page, you can do so by re-calling your search method using the value in `#last_evaluated_key`.
